version: '3.8'

services:
  db_postgres_core_note:
    image: postgres:16.3
    container_name: db_postgres_core_note
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: corenotes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - network_core_note
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "15433:80"
    networks:
      - network_core_note
    restart: unless-stopped

  backend_core_note:
    build: .
    container_name: backend_core_note
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db_postgres_core_note:5432/corenotes?schema=public"
    volumes:
      - .:/usr/app
    ports:
      - "3333:3333"
    networks:
      - network_core_note
    restart: unless-stopped

networks:
  network_core_note:

volumes:
  postgres_data:
